import type { Metadata } from "next";
import { Lora, Geist } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { NeonAuthUIProvider } from "@neondatabase/auth/react";
import { authClient } from "@/lib/auth/client";
import { UserButton } from "@neondatabase/auth/react";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", lora.className, "font-sans", geist.variable)} suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col ">
        <NeonAuthUIProvider authClient={authClient} defaultTheme="dark">
          <header className="borber-b border-[var(--border)] bg-[var(--surface)]/90 backdrop-blur">
            <div className="mx-auto flex h-16 w-full max-w-6xl items-center justify-between px-4">
              <Link href={"/"} className="text-sm font-semibold tracking-wide">Event Planner</Link>
              <nav className="flex items-center gap-4">
                <Link href={"/dashboard"} className="text-sm text-[var(--muted-foreground)]">Dashboard</Link>
                <UserButton size="icon" />
              </nav>
            </div>
          </header>

          <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col pz-4 py-8">{children}</main>

        </NeonAuthUIProvider>
      </body>
    </html>
  );
}
